name: Build PBRP

on:
  workflow_dispatch:
    inputs:
      MANIFEST_URL:
        description: Manifest URL
        required: true
        default: 'https://github.com/PitchBlackRecoveryProject/manifest_pb.git'
      MANIFEST_BRANCH:
        description: Manifest Branch
        required: true
        default: 'android-12.1'
      DEVICE_TREE_URL:
        description: Device Tree URL
        required: true
        default: 'https://github.com/saadelasfur/pbrp_device_samsung_m52xq.git'
      DEVICE_TREE_BRANCH:
        description: Device Tree Branch
        required: true
        default: 'android-12.1'
      DEVICE_PATH:
        description: Device Path
        required: true
        default: 'device/samsung/m52xq'
      DEVICE_NAME:
        description: Device Name
        required: true
        default: 'm52xq'
      MAKEFILE_NAME:
        description: Makefile Name
        required: true
        default: 'pb_m52xq'
      BUILD_TARGET:
        description: Build Target
        required: true
        default: 'recovery'
      PBRP_VERSION:
        description: PBRP Version
        required: true
        default: '4.0'

env:
  MANIFEST_URL: ${{ github.event.inputs.MANIFEST_URL }}
  MANIFEST_BRANCH: ${{ github.event.inputs.MANIFEST_BRANCH }}
  DEVICE_TREE_URL: ${{ github.event.inputs.DEVICE_TREE_URL }}
  DEVICE_TREE_BRANCH: ${{ github.event.inputs.DEVICE_TREE_BRANCH }}
  DEVICE_PATH: ${{ github.event.inputs.DEVICE_PATH }}
  DEVICE_NAME: ${{ github.event.inputs.DEVICE_NAME }}
  MAKEFILE_NAME: ${{ github.event.inputs.MAKEFILE_NAME }}
  BUILD_TARGET: ${{ github.event.inputs.BUILD_TARGET }}
  PBRP_VERSION: ${{ github.event.inputs.PBRP_VERSION }}

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    - name: Display Run Parameters
      run: |
        echo "::group::User Environment Variables"
        echo "Manifest URL: ${{ env.MANIFEST_URL }}"
        echo "Manifest Branch: ${{ env.MANIFEST_BRANCH }}"
        echo "Device Tree URL: ${{ env.DEVICE_TREE_URL }}"
        echo "Device Tree Branch: ${{ env.DEVICE_TREE_BRANCH }}"
        echo "Device Path: ${{ env.DEVICE_PATH }}"
        echo "Device Name: ${{ env.DEVICE_NAME }}"
        echo "Makefile Name: ${{ env.MAKEFILE_NAME }}"
        echo "Build Target: ${{ env.BUILD_TARGET }}.img"
        echo "PBRP Version: ${{ env.PBRP_VERSION }}"
        echo "::endgroup::"

    - name: Check Out
      uses: actions/checkout@v7

    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main

    - name: Prepare the environment
      run: |
        sudo apt update && sudo apt upgrade -y
        DEBIAN_FRONTEND=noninteractive sudo apt install -yq \
            linux-modules-extra-$(uname -r) \
            gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib \
            libc6-dev lib32ncurses-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils \
            xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses-dev libsdl1.2-dev \
            build-essential libgtk-3-dev libglu1-mesa-dev freeglut3-dev git libxml2 lzop pngcrush schedtool squashfs-tools \
            imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libncurses6 python3 tar

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 'latest'

    - name: Install OpenJDK
      uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Install repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Initialize repo
      run: |
        mkdir workspace
        cd workspace
        echo "WORKSPACE=$(pwd)" >> $GITHUB_ENV
        git config --global user.name "Saad"
        git config --global user.email "saadelasfur@gmail.com"
        repo init --depth=1 -u ${{ env.MANIFEST_URL }} -b ${{ env.MANIFEST_BRANCH }}

    - name: Repo Sync
      run: |
        cd ${{ env.WORKSPACE }}
        repo sync -j$(nproc --all) --force-sync

    - name: Clone device tree
      run: |
        cd ${{ env.WORKSPACE }}
        git clone ${{ env.DEVICE_TREE_URL }} -b ${{ env.DEVICE_TREE_BRANCH }} ./${{ env.DEVICE_PATH }}

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

    - name: Building recovery
      run: |
        cd ${{ env.WORKSPACE }}
        export ALLOW_MISSING_DEPENDENCIES=true
        source build/envsetup.sh
        lunch ${{ env.MAKEFILE_NAME }}-eng && make clean && mka pbrp -j$(nproc --all)

    - name: Set Date Variables
      run: |
        echo "DATE_SHORT=$(date +%Y%m%d)" >> $GITHUB_ENV
        echo "DATE_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
        echo "DATE_LONG=$(date +%Y%m%d-%H%M)" >> $GITHUB_ENV

    - name: Archive the files
      run: |
        cd ${{ env.WORKSPACE }}
        ls -a out/target/product/ && echo
        ls -a out/target/product/${{ env.DEVICE_NAME }}/ && echo
        cd out/target/product/${{ env.DEVICE_NAME }}
        tar -cvf PBRP-${{ env.DEVICE_NAME }}-${{ env.PBRP_VERSION }}-${{ env.DATE_LONG }}.tar ${{ env.BUILD_TARGET }}.img
        mv ${{ env.BUILD_TARGET }}.img PBRP-${{ env.DEVICE_NAME }}-${{ env.PBRP_VERSION }}-${{ env.DATE_LONG }}.img
        mv PBRP*.zip PBRP-${{ env.DEVICE_NAME }}-${{ env.PBRP_VERSION }}-${{ env.DATE_LONG }}.zip

    - name: Upload to Release
      uses: softprops/action-gh-release@v3
      with:
        files: | 
          workspace/out/target/product/${{ env.DEVICE_NAME }}/PBRP-${{ env.DEVICE_NAME }}-${{ env.PBRP_VERSION }}-${{ env.DATE_LONG }}.img
          workspace/out/target/product/${{ env.DEVICE_NAME }}/PBRP-${{ env.DEVICE_NAME }}-${{ env.PBRP_VERSION }}-${{ env.DATE_LONG }}.tar
          workspace/out/target/product/${{ env.DEVICE_NAME }}/PBRP-${{ env.DEVICE_NAME }}-${{ env.PBRP_VERSION }}-${{ env.DATE_LONG }}.zip
        name: pbrp-${{ env.DEVICE_NAME }}-${{ env.DATE_SHORT }}
        tag_name: ${{ env.DATE_TAG }}
        body: |
          Manifest: ${{ env.MANIFEST_BRANCH }}
          Device: ${{ env.DEVICE_NAME }}
          Target: ${{ env.BUILD_TARGET }}
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
