name: Build OrangeFox

on:
  workflow_dispatch:
    inputs:
      SYNC_URL:
        description: Sync URL
        required: true
        default: 'https://gitlab.com/OrangeFox/sync.git'
      MANIFEST_BRANCH:
        description: Manifest Branch
        required: true
        default: '12.1'
      DEVICE_TREE_URL:
        description: Device Tree URL
        required: true
        default: 'https://github.com/saadelasfur/orangefox_device_samsung_m52xq.git'
      DEVICE_TREE_BRANCH:
        description: Device Tree Branch
        required: true
        default: 'fox_12.1'
      DEVICE_PATH:
        description: Device Path
        required: true
        default: 'device/samsung/m52xq'
      DEVICE_NAME:
        description: Device Name
        required: true
        default: 'm52xq'
      MAKEFILE_NAME:
        description: Makefile Name
        required: true
        default: 'twrp_m52xq'
      BUILD_TARGET:
        description: Build Target
        required: true
        default: 'recovery'
      OFOX_VERSION:
        description: OFOX Version
        required: true
        default: 'R11.3_0_A14-Stable'

env:
  SYNC_URL: ${{ github.event.inputs.SYNC_URL }}
  MANIFEST_BRANCH: ${{ github.event.inputs.MANIFEST_BRANCH }}
  DEVICE_TREE_URL: ${{ github.event.inputs.DEVICE_TREE_URL }}
  DEVICE_TREE_BRANCH: ${{ github.event.inputs.DEVICE_TREE_BRANCH }}
  DEVICE_PATH: ${{ github.event.inputs.DEVICE_PATH }}
  DEVICE_NAME: ${{ github.event.inputs.DEVICE_NAME }}
  MAKEFILE_NAME: ${{ github.event.inputs.MAKEFILE_NAME }}
  BUILD_TARGET: ${{ github.event.inputs.BUILD_TARGET }}
  OFOX_VERSION: ${{ github.event.inputs.OFOX_VERSION }}

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    - name: Display Run Parameters
      run: |
        echo "::group::User Environment Variables"
        echo "Sync URL: ${{ env.SYNC_URL }}"
        echo "Manifest Branch: ${{ env.MANIFEST_BRANCH }}"
        echo "Device Tree URL: ${{ env.DEVICE_TREE_URL }}"
        echo "Device Tree Branch: ${{ env.DEVICE_TREE_BRANCH }}"
        echo "Device Path: ${{ env.DEVICE_PATH }}"
        echo "Device Name: ${{ env.DEVICE_NAME }}"
        echo "Makefile Name: ${{ env.MAKEFILE_NAME }}"
        echo "Build Target: ${{ env.BUILD_TARGET }}.img"
        echo "OFOX Version: ${{ env.OFOX_VERSION }}"
        echo "::endgroup::"

    - name: Check Out
      uses: actions/checkout@v7

    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 'latest'

    - name: Install OpenJDK
      uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Initialize workspace
      run: |
        mkdir workspace
        cd workspace
        echo "WORKSPACE=$(pwd)" >> $GITHUB_ENV

    - name: Prepare the build environment
      run: |
        cd ${{ env.WORKSPACE }}
        sudo apt update && sudo apt upgrade -y
        DEBIAN_FRONTEND=noninteractive sudo apt install -yq \
            linux-modules-extra-$(uname -r) \
            git python3 tar aria2
        git clone https://gitlab.com/OrangeFox/misc/scripts.git
        cd scripts
        sudo bash setup/android_build_env.sh
        sed -i 's/cd -/cd ../g' setup/install_android_sdk.sh
        sudo bash setup/install_android_sdk.sh

    - name: Sync OrangeFox sources and minimal manifest
      run: |
        cd ${{ env.WORKSPACE }}
        git clone ${{ env.SYNC_URL }}
        cd sync
        ./orangefox_sync.sh --branch ${{ env.MANIFEST_BRANCH }} --path ${{ env.WORKSPACE }}/fox_${{ env.MANIFEST_BRANCH }}

    - name: Clone device tree
      run: |
        cd ${{ env.WORKSPACE }}/fox_${{ env.MANIFEST_BRANCH }}
        git clone ${{ env.DEVICE_TREE_URL }} -b ${{ env.DEVICE_TREE_BRANCH }} ./${{ env.DEVICE_PATH }}

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

    - name: Building recovery
      run: |
        cd ${{ env.WORKSPACE }}/fox_${{ env.MANIFEST_BRANCH }}
        set +e
        export ALLOW_MISSING_DEPENDENCIES=true
        export FOX_BUILD_DEVICE=${{ env.DEVICE_NAME }}
        source build/envsetup.sh
        set -e
        lunch ${{ env.MAKEFILE_NAME }}-eng && make clean && mka adbd ${{ env.BUILD_TARGET }}image -j$(nproc --all)
      continue-on-error: true

    - name: Set Date Variables
      run: |
        echo "DATE_SHORT=$(date +%Y%m%d)" >> $GITHUB_ENV
        echo "DATE_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
        echo "DATE_LONG=$(date +%Y%m%d-%H%M)" >> $GITHUB_ENV

    - name: Archive the files
      run: |
        cd ${{ env.WORKSPACE }}
        ls -a fox_${{ env.MANIFEST_BRANCH }}/out/target/product/ && echo
        ls -a fox_${{ env.MANIFEST_BRANCH }}/out/target/product/${{ env.DEVICE_NAME }}/ && echo
        cd fox_${{ env.MANIFEST_BRANCH }}/out/target/product/${{ env.DEVICE_NAME }}
        tar -cvf OrangeFox-${{ env.OFOX_VERSION }}-${{ env.DEVICE_NAME }}.tar ${{ env.BUILD_TARGET }}.img
        mv ${{ env.BUILD_TARGET }}.img OrangeFox-${{ env.OFOX_VERSION }}-${{ env.DEVICE_NAME }}.img
        # mv OrangeFox*.zip OrangeFox-${{ env.OFOX_VERSION }}-${{ env.DEVICE_NAME }}.zip

    - name: Upload to Release
      uses: softprops/action-gh-release@v3
      with:
        files: |
          ${{ env.WORKSPACE }}/fox_${{ env.MANIFEST_BRANCH }}/out/target/product/${{ env.DEVICE_NAME }}/OrangeFox-${{ env.OFOX_VERSION }}-${{ env.DEVICE_NAME }}.img
          ${{ env.WORKSPACE }}/fox_${{ env.MANIFEST_BRANCH }}/out/target/product/${{ env.DEVICE_NAME }}/OrangeFox-${{ env.OFOX_VERSION }}-${{ env.DEVICE_NAME }}.tar
          ${{ env.WORKSPACE }}/fox_${{ env.MANIFEST_BRANCH }}/out/target/product/${{ env.DEVICE_NAME }}/OrangeFox-${{ env.OFOX_VERSION }}-${{ env.DEVICE_NAME }}.zip
        name: ofox-${{ env.DEVICE_NAME }}-${{ env.DATE_SHORT }}
        tag_name: ${{ env.DATE_TAG }}
        body: |
          Manifest: ${{ env.MANIFEST_BRANCH }}
          Device: ${{ env.DEVICE_NAME }}
          Target: ${{ env.BUILD_TARGET }}
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
